name: check-docker-task
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  workflow_dispatch:


jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@HEAD
      - run: export telegram_bot_token=6224529356:AAGRVh3k_EQn-7tW6qFrW_Fo1vcR1I2Z9JQ
      - run: docker build .
      - run: echo "The image of the server for the bot is created"